#!/bin/sh
# MyKAI Cloud Monitor — sends kaspad telemetry to MyKAI Insights + KasMap
# Upload this file to your cloud node's /app/data/ via Volume Browser
# Then run: sh /app/data/mykai-monitor.sh &
#
# Generated by MyKAI Node. Do not edit unless you know what you're doing.

# --- Configuration (baked in by MyKAI Node) ---
ACCOUNT_KEY="__ACCOUNT_KEY__"
KASMAP_TOKEN="__KASMAP_TOKEN__"
NODE_NAME="__NODE_NAME__"

# --- Constants ---
INSIGHTS_URL="https://mykai.dev/api/network/contribute"
KASMAP_URL="https://www.kasmap.org/api/node/heartbeat"
KASPACTL="/app/kaspactl -s localhost:15110 -a"
NODEID_FILE="/app/data/.mykai-nodeid"
POLL_INTERVAL=30
HEARTBEAT_INTERVAL=300
TMP_DIR="/tmp/mykai-monitor"

mkdir -p "$TMP_DIR"

# --- Generate or load Node ID ---
if [ -f "$NODEID_FILE" ]; then
  NODE_ID=$(cat "$NODEID_FILE")
else
  NODE_ID="cloud_$(head -c 16 /dev/urandom | od -An -tx1 | tr -d ' \n')"
  echo "$NODE_ID" > "$NODEID_FILE"
  echo "[MyKAI] Generated Node ID: $NODE_ID"
fi

echo "[MyKAI] Cloud Monitor starting"
echo "[MyKAI] Node ID: $NODE_ID"
# Truncate account key — it's a bearer credential for /api/nodes/status, and
# container stdout is forwarded to log aggregation on most cloud platforms.
# Mirrors src/headless/index.ts which redacts the same field.
echo "[MyKAI] Account Key: $(echo "$ACCOUNT_KEY" | cut -c1-8)..."
echo "[MyKAI] KasMap: $([ "$KASMAP_TOKEN" = "__KASMAP_TOKEN__" ] && echo 'not configured' || echo 'configured')"
echo "[MyKAI] Polling kaspad every ${POLL_INTERVAL}s, heartbeat every ${HEARTBEAT_INTERVAL}s"

# TLS warmup probe — if the container is missing a CA bundle, heartbeats
# would silently fail post-cert-validation re-enable. Surface the issue at
# startup with an actionable message instead.
if ! wget -q -O /dev/null --spider "$INSIGHTS_URL" 2>/dev/null; then
  echo "[MyKAI] WARN: TLS probe to $INSIGHTS_URL failed. Heartbeats may not deliver."
  echo "[MyKAI]       Install a CA bundle: 'apk add ca-certificates' or 'apt-get install ca-certificates'."
fi

# --- Helper: extract JSON field value ---
# Usage: json_val "fieldName" "$json_string"
# Handles: "field": "string", "field": number, "field": true/false/null
json_val() {
  echo "$2" | grep -o "\"$1\"[[:space:]]*:[[:space:]]*[\"]*[^,\"}]*" | head -1 | sed "s/\"$1\"[[:space:]]*:[[:space:]]*//;s/\"//g;s/[[:space:]]*$//"
}

# --- State ---
LAST_SINK=""
SINK_CHANGES=""
CHAIN_EVENTS=""
BLOCK_FIRST_SEEN=""
SINK_COUNT=0
START_TIME=$(date +%s)
LAST_HEARTBEAT=0
POLL_COUNT=0

# --- Main loop ---
while true; do
  NOW=$(date +%s)

  # Poll kaspad
  INFO=$($KASPACTL GetInfo 2>/dev/null)
  DAG=$($KASPACTL GetBlockDagInfo 2>/dev/null)

  if [ -z "$INFO" ] || [ -z "$DAG" ]; then
    if [ $((POLL_COUNT % 10)) -eq 0 ]; then
      echo "[MyKAI] Waiting for kaspad to be ready..."
    fi
    POLL_COUNT=$((POLL_COUNT + 1))
    sleep "$POLL_INTERVAL"
    continue
  fi

  # Parse fields
  IS_SYNCED=$(json_val "isSynced" "$INFO")
  SERVER_VERSION=$(json_val "serverVersion" "$INFO")
  MEMPOOL_SIZE=$(json_val "mempoolSize" "$INFO")
  DAA_SCORE=$(json_val "virtualDaaScore" "$DAG")
  NETWORK=$(json_val "networkName" "$DAG")
  PRUNING_HASH=$(json_val "pruningPointHash" "$DAG")
  # Sink hash: use first tipHash as proxy (kaspactl doesn't expose "sink" directly)
  SINK_HASH=$(echo "$DAG" | grep -o '"tipHashes"[[:space:]]*:[[:space:]]*\[[[:space:]]*"[^"]*"' | head -1 | grep -o '"[^"]*"$' | tr -d '"')
  BLOCK_COUNT=$(json_val "blockCount" "$DAG")
  HEADER_COUNT=$(json_val "headerCount" "$DAG")

  # Get peer count from tip hashes (rough proxy) — actual peer count needs getConnectedPeerInfo
  # which kaspactl doesn't return a count for easily. Use 0 for now.
  PEER_INFO=$($KASPACTL GetConnectedPeerInfo 2>/dev/null)
  PEER_COUNT=$(echo "$PEER_INFO" | grep -c '"id"' 2>/dev/null || echo "0")

  # Determine status
  if [ "$IS_SYNCED" = "true" ]; then
    STATUS="synced"
  else
    STATUS="syncing"
  fi

  # Track sink changes
  if [ -n "$LAST_SINK" ] && [ "$SINK_HASH" != "$LAST_SINK" ]; then
    TS=$(date +%s)000
    if [ -n "$SINK_CHANGES" ]; then
      SINK_CHANGES="${SINK_CHANGES},"
      CHAIN_EVENTS="${CHAIN_EVENTS},"
      BLOCK_FIRST_SEEN="${BLOCK_FIRST_SEEN},"
    fi
    SINK_CHANGES="${SINK_CHANGES}{\"hash\":\"${SINK_HASH}\",\"previousHash\":\"${LAST_SINK}\",\"daaScore\":${DAA_SCORE:-0},\"ts\":${TS}}"
    CHAIN_EVENTS="${CHAIN_EVENTS}{\"removed\":[],\"added\":[\"${SINK_HASH}\"],\"ts\":${TS}}"
    BLOCK_FIRST_SEEN="${BLOCK_FIRST_SEEN}{\"hash\":\"${SINK_HASH}\",\"ts\":${TS}}"
    SINK_COUNT=$((SINK_COUNT + 1))
  fi
  LAST_SINK="$SINK_HASH"

  POLL_COUNT=$((POLL_COUNT + 1))

  # Send heartbeat every HEARTBEAT_INTERVAL seconds
  ELAPSED=$((NOW - LAST_HEARTBEAT))
  if [ "$ELAPSED" -ge "$HEARTBEAT_INTERVAL" ] || [ "$LAST_HEARTBEAT" -eq 0 ]; then
    UPTIME=$((NOW - START_TIME))

    # Build payload
    PAYLOAD="{\"nodeId\":\"${NODE_ID}\",\"nodeName\":\"${NODE_NAME}\",\"accountKey\":\"${ACCOUNT_KEY}\",\"heartbeatMode\":\"normal\",\"isPublic\":true,\"network\":\"${NETWORK:-mainnet}\",\"status\":\"${STATUS}\",\"daaScore\":${DAA_SCORE:-0},\"uptimeSeconds\":${UPTIME},\"nodeVersion\":\"${SERVER_VERSION}\",\"peerCount\":${PEER_COUNT:-0},\"mempoolSize\":${MEMPOOL_SIZE:-0},\"sinkHash\":\"${SINK_HASH}\",\"pruningPointHash\":\"${PRUNING_HASH}\",\"raw\":{\"sinkChanges\":[${SINK_CHANGES}],\"chainEvents\":[${CHAIN_EVENTS}],\"blockFirstSeen\":[${BLOCK_FIRST_SEEN}]}}"

    # Send to Insights — TLS verification ON (mykai.dev has a valid cert).
    # `--no-check-certificate` was previously here and exposed the account
    # key to MITM. If the container's CA bundle is missing, the startup
    # probe above will warn the operator with a fix command.
    wget -q -O /dev/null --post-data="$PAYLOAD" \
      --header="Content-Type: application/json" \
      "$INSIGHTS_URL" 2>&1
    INSIGHTS_OK=$?

    # Send to KasMap (if token configured)
    KASMAP_OK="-"
    if [ "$KASMAP_TOKEN" != "__KASMAP_TOKEN__" ] && [ -n "$KASMAP_TOKEN" ]; then
      KASMAP_PAYLOAD="{\"nodeId\":\"${NODE_ID}\",\"nodeName\":\"${NODE_NAME}\",\"status\":\"${STATUS}\",\"daaScore\":${DAA_SCORE:-0},\"kaspadVersion\":\"${SERVER_VERSION}\",\"isPublic\":true,\"uptimeSeconds\":${UPTIME},\"blocksValidated\":0,\"transactionsSeen\":0}"
      wget -q -O /dev/null --post-data="$KASMAP_PAYLOAD" \
        --header="Content-Type: application/json" \
        --header="Authorization: Bearer ${KASMAP_TOKEN}" \
        "$KASMAP_URL" 2>&1
      KASMAP_OK=$?
    fi

    echo "[MyKAI] Heartbeat sent — status=${STATUS} daa=${DAA_SCORE} peers=${PEER_COUNT} sinks=${SINK_COUNT} insights=$([ $INSIGHTS_OK -eq 0 ] && echo 'ok' || echo 'fail') kasmap=${KASMAP_OK}"

    # Reset buffers
    SINK_CHANGES=""
    CHAIN_EVENTS=""
    BLOCK_FIRST_SEEN=""
    SINK_COUNT=0
    LAST_HEARTBEAT=$NOW
  fi

  sleep "$POLL_INTERVAL"
done
